#pragma once

#include "drvcommon.h"

#define DEVICE_NAME			"\\Device\\CRARKSYS"
#define SYMLINK_NAME		"\\DosDevices\\CRARKSYS"
PRESET_UNICODE_STRING(usDeviceName, DEVICE_NAME);
PRESET_UNICODE_STRING(usSymlinkName, SYMLINK_NAME);

#ifndef FILE_DEVICE_CRARKSYS
#define FILE_DEVICE_CRARKSYS 0x800
#endif

// Values defined for "Method"
// METHOD_BUFFERED
// METHOD_IN_DIRECT
// METHOD_OUT_DIRECT
// METHOD_NEITHER
// 
// Values defined for "Access"
// FILE_ANY_ACCESS
// FILE_READ_ACCESS
// FILE_WRITE_ACCESS

#define IOCTL_CRARKSYS_HELLO CTL_CODE(FILE_DEVICE_CRARKSYS, 0x01, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_CRARKSYS_SPEINIT CTL_CODE(FILE_DEVICE_CRARKSYS, 0x02, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
