#pragma once

#ifndef FILE_DEVICE_CRARKSYS
#define FILE_DEVICE_CRARKSYS 0x800
#endif

#define IOCTL_CRARKSYS_HELLO CTL_CODE(FILE_DEVICE_CRARKSYS, 0x01, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_CRARKSYS_SPEINIT CTL_CODE(FILE_DEVICE_CRARKSYS, 0x02, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_CRARKSYS_PROCENUM CTL_CODE(FILE_DEVICE_CRARKSYS, 0x03, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_CRARKSYS_THREADENUM CTL_CODE(FILE_DEVICE_CRARKSYS, 0x04, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_CRARKSYS_QUERYPROCNAME CTL_CODE(FILE_DEVICE_CRARKSYS, 0x05, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)
#define IOCTL_CRARKSYS_QUERYPROCINFO CTL_CODE(FILE_DEVICE_CRARKSYS, 0x06, METHOD_NEITHER, FILE_READ_DATA | FILE_WRITE_DATA)